### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by 220m** [mishalhossin/Discord-AI-Chatbot#116] opened 2023-06-01 11:55 UTC
Hey, with the new version I am getting this error.

D:\AI\Discord AI\Discord-AI-Chatbot>python main.py
Traceback (most recent call last):
  File "D:\AI\Discord AI\Discord-AI-Chatbot\main.py", line 42, in <module>
    file_content = file.read()
                   ^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 80: character maps to <undefined>

**Comment by mishalhossin** [comment] 2023-06-01 23:52
We have identified the problem you encountered, and it has been resolved in the following commit : [68d23add388e878c86ca2bfa1c0ba2814923b312](https://github.com/mishalhossin/Discord-AI-Chatbot/commit/68d23add388e878c86ca2bfa1c0ba2814923b312).

To resolve the error, please update your codebase with the latest changes from the commit mentioned above. This fix addresses the `UnicodeDecodeError` caused by the 'charmap' codec being unable to decode a specific byte.

**Closed by mishalhossin** 2023-06-01 23:52 UTC
