### ISSUE TITLE
"charmap" codec error on stat

### ISSUE THREAD

**Issue by YuvrajxGarg** [mishalhossin/Discord-AI-Chatbot#118] opened 2023-06-01 14:35 UTC
![image](https://github.com/mishalhossin/Discord-AI-Chatbot/assets/86508367/f24fd238-3822-4511-8a6f-8bf3579a57a8)

**Comment by mishalhossin** [comment] 2023-06-01 23:52
We have identified the problem you encountered, and it has been resolved in the following commit : [68d23add388e878c86ca2bfa1c0ba2814923b312](https://github.com/mishalhossin/Discord-AI-Chatbot/commit/68d23add388e878c86ca2bfa1c0ba2814923b312).

To resolve the error, please update your codebase with the latest changes from the commit mentioned above. This fix addresses the `UnicodeDecodeError` caused by the `charmap` codec being unable to decode a specific byte.

**Closed by mishalhossin** 2023-06-01 23:52 UTC
